version: "3.7"

services:

    flask:
      build: ./flaskapp
      container_name: capstoneflaskproject
      restart: always
      environment:
        - APP_NAME=MyFlaskApp
      expose:
        - 8080