version: "3.7"

services:

    flask:
      build: ./scavyapp
      container_name: scavyapp
      restart: always
      environment:
        - APP_NAME=MyFlaskApp
      expose:
        - 8080
      ports:
        - 8080

    nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
        - "80:80"

    sql-db:
      build: ./Database 
      container_name: mysql-container-scavyapp
      image: mysql:latest
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpass
      expose:
          - 3306
      ports:
          -  "3306:3306"
      volumes:
          - sql-volumes:/var/lib/mysql

volumes:
  sql-volumes:

